config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }

  root 'site#index'

  get 'privacy' => 'site#privacy'
  get 'terms'   => 'site#terms'

  # routes for URL
  post 'url'    => 'url#create'
  get  'url'    => 'url#index'

  # Contact Us
  get 'contact' => 'contacts#new'
  post 'contact' => 'contacts#create'
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  validates :name, :presence => true
  validates :email, :presence => true
  validates :message, :presence => true
end

app/models/url.rb
class Url < ActiveRecord::Base
  before_save :check_url_http, :convert_url

  validate :check_com

  def check_url_http
    self.original = 'http://' + self.original
  end

  def check_com
    unless self.original.include? ".com"
      self.errors.add :base, "the original URL should contain .com"
    end
  end

  def convert_url
    self.converted = 'http://localhost:3000/' + random_string
  end

  def random_string
    (0...6).map { (65 + rand(26)).chr }.join
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :first_name, presence: true
  validates :last_name, presence: true

  has_attached_file :avatar, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  protect_from_forgery with: :null_session

  def new
  end

  def create
    @contact = Contact.new
    @contact.name = params[:name]
    @contact.email = params[:email]
    @contact.subject = params[:subject]
    @contact.message = params[:message]

    if @contact.save
      # Send Email
      UserMailer.contact_us_email(@contact).deliver
    else
      flash.now[:alert] = 'There is an error'
    end
  end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:avatar, :first_name, :last_name, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:avatar, :first_name, :last_name, :email, :password, :password_confirmation, :current_password)
  end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController

  def index
  end

  def privacy
  end

  def terms
  end

end

app/controllers/url_controller.rb
class UrlController < ApplicationController
  protect_from_forgery with: :null_session

  before_action :authenticate_user!, :except => [:create]

  def index
  end

  def create
    @url = Url.new
    @url.original = params[:url]

    if @url.save
      render :create
    else
      # where to go
      render :text, "Error"
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper


  def flash_noty_script_tag
    unless flash.empty?
      noties = flash.map do |name, message|
        if message.is_a?(String) || message.is_a?(ActiveModel::Errors)
          type = ( name == :notice ? "success" : "error" )
          timeout = ( name == :notice ? 4000 : 30000 )
          text = ( message.is_a?(ActiveModel::Errors) ? "It's an error object" : message )

          "noty({ layout: 'top', type: '" + type +
          "', timeout: " + timeout.to_s +
          ", text: \"" + text +
          "\"});"
        end
      end

      javascript_tag( "$(function() {\n  " + noties.join("\n  ") + "\n});")
    end
  end

  def nav_link(link_text, link_path)
    class_name = current_page?(link_path) ? 'active' : ''

    content_tag(:li, :class => class_name) do
      link_to link_text, link_path
    end
  end

end

app/views/layouts/_messages.html.erb
<%
flash.each do |name, message|
  if message.is_a?(String) || message.is_a?(ActiveModel::Errors)
    notyType = (name == :notice ? "success" : "error")
    notyTimeout = (name == :notice ? 4000 : 30000)

    if message.is_a?(ActiveModel::Errors)
      notyText = "It's an error object"
    else
      notyText = message
    end
  end
%>

<%= javascript_tag do %>
    $(function() {
      noty({
        layout: 'top',
        type: "<%= notyType %>",
        timeout: "<%= notyTimeout %>",
        text: "<%= notyText %>"
      });
    });
<% end %>
<%
end
%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Shawty</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">Shawty</a>
      </div>
      <div class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          <li class="active"><%= nav_link 'Home', root_path %></li>
          <% if user_signed_in? %>
          <li><%= nav_link 'URL List', url_path %></li>
          <% end %>
          <li><%= nav_link 'Privacy', privacy_path %></li>
          <li><%= nav_link 'Terms', terms_path %></li>
          <li><%= nav_link 'Contact', contact_path %></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
            <li>Logged in as <strong><%= current_user.email %></strong>.</li>
            <li><%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %></li>
            <li><%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %></li>
          <% else %>
            <li><%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %></li>
            <li><%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %></li>
          <% end %>
        </ul>
      </div><!--/.nav-collapse -->


    </div>
  </div>

  <div class="container">

    <div class="starter-template">
      <h1>Bootstrap starter template</h1>
      <p class="lead">Use this document as a way to quickly start any new project.<br> All you get is this text and a mostly barebones HTML document.</p>
    </div>
    <div>

    <%= yield %>

    </div>

  </div>

<%= flash_noty_script_tag %>

</body>
</html>